"""initial

Revision ID: 7edc8d1c1fda
Revises: 
Create Date: 2026-07-14 12:58:59.389608

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7edc8d1c1fda'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('norms', sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Flexible numeric constants: bag_price_uzs, bag_kg, rate_kg_m2, piece_price_uzs, piece_m, roll_width_m, roll_length_m, pack_m2, points_default, avg_run_m, slack, price_per_m_uzs, etc.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('norms', 'params')
    # ### end Alembic commands ###
